# name: remote ssh command
# on: [push]
# jobs:
#   build:
#     name: Build
#     runs-on: [self-hosted, linux, x64]
#     steps:
#     - uses: actions/checkout@master
#     - name: executing remote ssh commands using ssh key
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.AIRFLOW_HOST }}
#         username: ${{ secrets.AIRFLOW_USER }}
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         script: |
#           cd ~/airflow-tasks
#           sh deploy.sh
#           echo "deploy end"
